version: '3'

services:
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_REPO=${COMPOSER_REPO}
        - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
    container_name: php-web
    ports:
      - "9000:9000"
    volumes:
      - ${PROJECT_DIR}:${DOCKER_PROJECT_DIR}
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    privileged: true
    networks:
      - frontend
      - backend

  nginx:
    container_name: nginx-web
    image: "nginx:${NGINX_VERSION}"
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ${PROJECT_DIR}:${DOCKER_PROJECT_DIR}
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    links:
      - php
    networks:
      - frontend
      - backend

  mysql:
    container_name: mysql-web
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend

  redis:
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    container_name: redis-web
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis:/usr/local/redis
      #- ./redis/redis.conf:/usr/local/etc/redis.conf
      #- ./redis/data:/usr/local/redis/data
      #- ./redis/redis.log:/usr/local/redis/redis.log
    restart: always
    privileged: true
    networks:
      - backend

  mongo:
    build:
      context: ./mongo
      args:
        - MONGODB_VERSION=${MONGODB_VERSION}
    ports:
      - "${MONGODB_PORT}:27017"
    container_name: mongo-web
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./mongo/db:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:


