version: '3'

services:
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_REPO=${COMPOSER_REPO}
    container_name: "phpfpm-web"
    ports: 
      - "9000:9000" 
    volumes: 
      - ../data/www:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    privileged: true
    networks:
      - net-php
      - net-mysql
      - net-redis

  web:
    container_name: nginx-web
    image: 'nginx'
    ports:
      - "${NGINX_PORT}:80"
    volumes: 
      - ../data/www:/usr/share/nginx/html:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    links:
      - php
    networks:
      - net-php
        
  mysql: 
    container_name: "mysql-web"
    image: mysql:${MYSQL_VERSION}
    ports: 
      - "${MYSQL_PORT}:3306" 
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - net-mysql

  redis:
    container_name: "redis-web"
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/log/redis.log:/var/log/redis/redis.log
    restart: always
    privileged: true
    networks:
      - net-redis
networks:
  net-php:
  net-mysql:
  net-redis:


