version: '3'

services:
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_REPO=${COMPOSER_REPO}
    container_name: php-web
    ports:
      - "9000:9000"
    volumes:
      - ${PROJECT_DIR}:${DOCKER_PROJECT_DIR}
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    privileged: true
    networks:
      - frontend
      - backend

  nginx:
    container_name: nginx-web
    image: "nginx:${NGINX_VERSION}"
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ${PROJECT_DIR}:${DOCKER_PROJECT_DIR}:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    links:
      - php
    networks:
      - frontend

  mysql:
    container_name: mysql-web
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend

  redis:
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    container_name: redis-web
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.log:/usr/local/redis/redis.log
    restart: always
    privileged: true
    networks:
      - backend
networks:
  frontend:
  backend:


